### ISSUE TITLE
broken pkgconfig files

### ISSUE THREAD

**Issue by tjelbert** [latchset/libverto#25] opened 2019-01-19 14:39 UTC
they currently install as:

prefix=/usr
libdir=${exec_prefix}/lib
includedir=${prefix}/include
exec_prefix=${prefix}

but this means that libdir references a nonexistent exec_prefix. 
This in turn breaks compiling krb5, which does

pkg-config  --print-errors --cflags --libs "libverto"
Variable 'exec_prefix' not defined in '/usr/lib/pkgconfig/libverto.pc'

**Comment by frozencemetery** [comment] 2019-01-21 17:19
Can you give me more information here?  These packageconfig files work fine for Debian and Fedora.  That is:

```
rharwood@seton:~$ pkg-config --print-errors --cflags --libs "libverto"
-lverto
rharwood@seton:~$ cat /etc/debian_version 
buster/sid
rharwood@seton:~$ 
```

**Comment by frozencemetery** [comment] 2019-01-22 17:52
Let me be as clear as I can.  In order to fix whatever issue you have here, I need to understand (1) what environment you're running in and (2) what the actual problem is.  The easiest way for me to get that understanding is to tell me exactly what you did, including information such as distro and versions.  In particular, I don't know what *ships* 0.29.2; Debian ships patched 0.29, and Fedora has (what it claims is) 1.5.4.  Both of these versions do not reproduce the issue you claim.

**Comment by tjelbert** [comment] 2019-01-22 19:43
pkgconfig is the latest upstream version, released 
[vert.zip](https://github.com/latchset/libverto/files/2784330/vert.zip)

in 2017, from
http://www.freedesktop.org/software/pkgconfig/releases

I run built from source, http://sourcemage.org/, 
bash-5
gcc-8.2
linux-4.20
Almost everthing is the latest upsteam version, unpatched.
Everything else is happy with this version of pkgconfig.

I attach the compile log from when I built libverto

**Comment by tjelbert** [comment] 2019-01-22 19:46
the 
[verto.zip](https://github.com/latchset/libverto/files/2784339/verto.zip)
actual log

**Comment by frozencemetery** [comment] 2019-01-23 17:30
I'm not sure why you closed this.

As an aside, you're going to want to fix whatever's wrong with libev.  Also, whatever build procedure you're invoking appears to run ./configure multiple times, which is probably a mistake.

**Comment by frozencemetery** [comment] 2019-01-23 17:51
Upon further inspection, you're having a different problem than I thought.  Your build appears to not be expanding variables in the .pc file from autotools.  It looks like a substitution issue in your buildsystem perhaps?  Compare the libverto.pc.in file in the repository to what you have installed, and also take a look at this:

```
[root@hide pkg-config-0.29.2]# PKG_CONFIG_PATH=/usr/lib64/pkgconfig ./pkg-config --print-errors --cflags --libs libverto
-L/usr/lib64 -lverto
[root@hide pkg-config-0.29.2]# ./pkg-config --version
0.29.2
[root@hide pkg-config-0.29.2]# cat /usr/lib64/pkgconfig/libverto.pc 
prefix=/usr
libdir=/usr/lib64
includedir=/usr/include
exec_prefix=/usr
 
Name: libverto
Description: Event loop abstraction interface
Version: 0.3.0
Libs: -L${libdir} -lverto
Cflags: -I${includedir}
Libs.private: -ldl 
[root@hide pkg-config-0.29.2]# 
```

**Comment by tjelbert** [comment] 2019-01-24 12:35
If I rearrange libverto.pc,in to be
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@

configure generates:
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

which looks correct, however the original file generates:

prefix=/usr/local
libdir=${exec_prefix}/lib
includedir=${prefix}/include
exec_prefix=${prefix}

In that case there is a forward reference from libdir to exec_prefix, which triggers my problem.

This may well be a bug in autoconf-2.69

**Comment by frozencemetery** [comment] 2019-01-25 18:02
Unfortunately I do tend to agree that it's likely an autoconf bug.  From your logs, you invoke configure like this:

```
./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-pc-linux-gnu build_alias=x86_64-pc-linux-gnu CFLAGS=-march=native -mtune=native -m64 -pipe -O3 LDFLAGS= CPPFLAGS= --no-create --no-recursion
```

Ignoring that you've specified /usr there and not /usr/local (as per your comment above?), autoconf apears to be replacing `@exec_prefix@` with `${exec_prefix}` and such, which to me looks like a level of variable expansion is missing.

**Comment by dilyanpalauzov** [comment] 2019-06-03 18:46
I confirm, `pkg-config --exists --print-errors libverto; echo $?` prints with pkg-config 0.29.2:
```
Variable 'exec_prefix' not defined in '/usr/local/lib/pkgconfig/libverto.pc'
1
```
until I move `exec_prefix=` right after `prefix=`.

**Closed** 2019-06-03 20:06 UTC
